# Generated by Django 4.2.8 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0005_alter_yemek_restoran'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahalleYemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullaniciadi', models.CharField(max_length=100, null=True)),
                ('yemekadi', models.TextField(blank=True, null=True)),
                ('resim', models.ImageField(null=True, upload_to='mahalle_images')),
            ],
        ),
    ]
